# YAML file from https://dev.to/renegadecoder94/how-to-build-latex-with-travis-ci-and-minted-39ff
# See also https://github.com/PHPirates/travis-ci-latex-pdf
language: generic
# Dependency of the minted package
before_install:
  - sudo apt-get install python-pygments
install:
  - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR
script:
  - pdflatex --shell-escape -synctex=1 -interaction=nonstopmode ./master.tex
  - biber ./master
  - pdflatex --shell-escape -synctex=1 -interaction=nonstopmode ./master.tex
deploy:
  provider: releases
  api_key:
    secure:  d6aa298c152968d809e774da2e48604988f09784
  file:
    - ./master.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email: false
