# YAML file from https://dev.to/renegadecoder94/how-to-build-latex-with-travis-ci-and-minted-39ff
# See also https://github.com/PHPirates/travis-ci-latex-pdf
# We test each method for building LaTeX in a separate job.
language: generic

dist: bionic

before_install:
  - sudo apt-get install python-pygments
install:
  - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR
script:
  # Texliveonfly will download packages automatically
  - texliveonfly ./master.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - latexmk -pdf ./master.tex
  
  #- pdflatex --shell-escape -synctex=1 -interaction=nonstopmode ./master.tex
  #- biber ./master
  #- pdflatex --shell-escape -synctex=1 -interaction=nonstopmode ./master.tex

# Uncomment the following lines to see the packages installed in travis
after_script:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'
  
deploy:
  provider: releases
  api_key:
    secure:  d6aa298c152968d809e774da2e48604988f09784
  file:
    - ./master.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email: false
