# YAML file from https://dev.to/renegadecoder94/how-to-build-latex-with-travis-ci-and-minted-39ff
# See also https://github.com/PHPirates/travis-ci-latex-pdf
# We test each method for building LaTeX in a separate job.
language: generic

dist: bionic

before_install:
  - sudo apt-get install python-pygments
install:
  - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR
script:
  # Texliveonfly will download packages automatically
  - texliveonfly ./master.tex --compiler=pdflatex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  #- latexmk -pdflua -interaction=nonstopmode ./master.tex
  
  # Run PDFLaTeX combined with biber few times to fix all references. 
  # Expect error until the last command (from Travis to not report error)
  - pdflatex -interaction=nonstopmode master.tex || true
  - bibtex master || true
  - pdflatex -interaction=nonstopmode  master.tex || true
  - pdflatex -interaction=nonstopmode master.tex # Compile twice to fix references

## Uncomment the following lines to see the packages installed in travis
#after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'

deploy:
  provider: releases
  api_key:
    secure: JJxinuqYrHySqN+zePYquu/j+T5LtJRoKDPH7mF5LAtH+LX7nMXWIwe2q8Fz1OW0+U5BkMpKw1EFZMrTG/H34hY90O7vLLqBA8APkgiDpW3xEoOEiYDohbjAd2SmnoSo4BFgz5/UrDAW2n+AM0yEtv86XEPKdZJQypEN65sAntcEbBKX1E2mBsinZb0Ct3gXzKqQzz0eEq5Qjn3tudrX9FBa40nBsOUeAeHIVoPyGG+X7cwye40gev513MNra0dYEBUSUxX3KmxaPHjYoTiy1fYHagMEmiQdW9OmCrd5DDRaTMJosqqgARUdof1xNrxn7A9Pb6roW2NF8q82zVuNJBjkzSiNFFgu0gcebSh5xG32+l86Tpo7V9UhafFX2qWayBj4ZKdxEQCoLN6SOOqY/13P8nJ4iP8AurTmMBXFb+jp5TVlaOMpILsqFdEvySFtO1p61nx3ClSrF4fegDjwIKvxls1rGlwwmMD0MVy76O1mvqkGnfTqCIaZ9Ych8EibrTM6/vatxigU112paq/WjSI6/jtpAveKGYptWGVG/DmqHAHoKEFthZb2q2m1zGUuQYP77mbrIsWO6HnwcBWUvMOTy4Ei4HxdzLnTfIVUURZJgdKIFIo6jcrdCHUmlyfJUbEqxUZgt1xc4YursqdOpctQWD/JxeCXjDL6nXlJeUQ=
  file:
    - ./master.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email: false
